dist: trusty
sudo: required
language: cpp
script: make test
before_install:
    - sudo apt-get update
    - sudo apt-get install python3
addons:
    apt:
        packages:
            - libboost-all-dev